### ISSUE TITLE
"singleton can't be dumped" exception when trying to cache a BatchLoader field

### ISSUE THREAD

**Issue by freestyl3r** [stackshareio/graphql-cache#38] opened 2018-11-20 16:15 UTC
Hello. When using [BatchLoader](https://github.com/exAspArk/batch-loader) gem to... batch load a field, the following error is returned when trying to cache it:

```Unhandled error during GraphQL execution:

  singleton can't be dumped
    /home/billk/.gem/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/cache.rb:665:in `dump'
    /home/billk/.gem/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/cache.rb:665:in `dup_value!'
    /home/billk/.gem/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/cache/memory_store.rb:130:in `write_entry'
    /home/billk/.gem/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/cache.rb:400:in `block in write'
    ...
```
I haven't tested with https://github.com/Shopify/graphql-batch. Maybe there is a problem with lazy fields in general?

**Comment by uzzer** [comment] 2019-02-20 07:03
I have the same issue when using `Rails.cache` without this gem, so the problem is somewhere above.

**Comment by uzzer** [comment] 2019-02-20 09:27
In my case, the reason was the fact that only serializable objects could be cached. e.g. I did try to cache FactoryBot `build_stubbed` thing. @freestyl3r please check is it your case

**Comment by freestyl3r** [comment] 2019-02-21 11:08
Yeah, it's a limitation of [Marshal](http://ruby-doc.org/core-2.6.1/Marshal.html]) used internally by rails cache.

>Some objects cannot be dumped: if the objects to be dumped include bindings, procedure or method objects, instances of class IO, or singleton objects, a TypeError will be raised.

If we provide `marshal_dump` & `marshal_load` methods, maybe we can make this work.

**Comment by thebadmonkeydev** [comment] 2019-02-28 13:21
Since this is a problem with `Rails.cache` and not graphql-cache, I'm going to close this issue.

**Closed by thebadmonkeydev** 2019-02-28 13:21 UTC
